/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu_1' in SOPC Builder design 'ECE423_QSYS'
 * SOPC Builder design path: ../../ECE423_QSYS.sopcinfo
 *
 * Generated: Tue Mar 26 21:43:42 EDT 2019
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x21000820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 125000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1e
#define ALT_CPU_DCACHE_BYPASS_MASK 0x80000000
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 16384
#define ALT_CPU_EXCEPTION_ADDR 0x210c0020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 125000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 1
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_DIVISION_ERROR_EXCEPTION
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0x1e
#define ALT_CPU_NAME "cpu_1"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x210c0000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x21000820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 125000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x1e
#define NIOS2_DCACHE_BYPASS_MASK 0x80000000
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 16384
#define NIOS2_EXCEPTION_ADDR 0x210c0020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 1
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_DIVISION_ERROR_EXCEPTION
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0x1e
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x210c0000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_MAILBOX_SIMPLE
#define __ALTERA_GENERIC_TRISTATE_CONTROLLER
#define __ALTERA_MEM_IF_LPDDR2_EMIF
#define __ALTERA_MSGDMA
#define __ALTERA_NIOS2_GEN2


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart_1"
#define ALT_STDERR_BASE 0x21001000
#define ALT_STDERR_DEV jtag_uart_1
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart_1"
#define ALT_STDIN_BASE 0x21001000
#define ALT_STDIN_DEV jtag_uart_1
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart_1"
#define ALT_STDOUT_BASE 0x21001000
#define ALT_STDOUT_DEV jtag_uart_1
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "ECE423_QSYS"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_1 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_1 altera_avalon_jtag_uart
#define JTAG_UART_1_BASE 0x21001000
#define JTAG_UART_1_IRQ 0
#define JTAG_UART_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_1_NAME "/dev/jtag_uart_1"
#define JTAG_UART_1_READ_DEPTH 64
#define JTAG_UART_1_READ_THRESHOLD 8
#define JTAG_UART_1_SPAN 256
#define JTAG_UART_1_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_1_WRITE_DEPTH 64
#define JTAG_UART_1_WRITE_THRESHOLD 8


/*
 * lpddr2 configuration
 *
 */

#define ALT_MODULE_CLASS_lpddr2 altera_mem_if_lpddr2_emif
#define LPDDR2_BASE 0x0
#define LPDDR2_IRQ -1
#define LPDDR2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define LPDDR2_NAME "/dev/lpddr2"
#define LPDDR2_SPAN 536870912
#define LPDDR2_TYPE "altera_mem_if_lpddr2_emif"


/*
 * mailbox_simple_0_1 configuration
 *
 */

#define ALT_MODULE_CLASS_mailbox_simple_0_1 altera_avalon_mailbox_simple
#define MAILBOX_SIMPLE_0_1_BASE 0x20000050
#define MAILBOX_SIMPLE_0_1_IRQ 3
#define MAILBOX_SIMPLE_0_1_IRQ_INTERRUPT_CONTROLLER_ID 0
#define MAILBOX_SIMPLE_0_1_NAME "/dev/mailbox_simple_0_1"
#define MAILBOX_SIMPLE_0_1_SPAN 16
#define MAILBOX_SIMPLE_0_1_TYPE "altera_avalon_mailbox_simple"


/*
 * mailbox_simple_1_0 configuration
 *
 */

#define ALT_MODULE_CLASS_mailbox_simple_1_0 altera_avalon_mailbox_simple
#define MAILBOX_SIMPLE_1_0_BASE 0x20000060
#define MAILBOX_SIMPLE_1_0_IRQ -1
#define MAILBOX_SIMPLE_1_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MAILBOX_SIMPLE_1_0_NAME "/dev/mailbox_simple_1_0"
#define MAILBOX_SIMPLE_1_0_SPAN 16
#define MAILBOX_SIMPLE_1_0_TYPE "altera_avalon_mailbox_simple"


/*
 * read_dma_cb_csr configuration
 *
 */

#define ALT_MODULE_CLASS_read_dma_cb_csr altera_msgdma
#define READ_DMA_CB_CSR_BASE 0x20000000
#define READ_DMA_CB_CSR_BURST_ENABLE 1
#define READ_DMA_CB_CSR_BURST_WRAPPING_SUPPORT 0
#define READ_DMA_CB_CSR_CHANNEL_ENABLE 0
#define READ_DMA_CB_CSR_CHANNEL_ENABLE_DERIVED 0
#define READ_DMA_CB_CSR_CHANNEL_WIDTH 8
#define READ_DMA_CB_CSR_DATA_FIFO_DEPTH 512
#define READ_DMA_CB_CSR_DATA_WIDTH 1024
#define READ_DMA_CB_CSR_DESCRIPTOR_FIFO_DEPTH 16
#define READ_DMA_CB_CSR_DMA_MODE 1
#define READ_DMA_CB_CSR_ENHANCED_FEATURES 0
#define READ_DMA_CB_CSR_ERROR_ENABLE 0
#define READ_DMA_CB_CSR_ERROR_ENABLE_DERIVED 0
#define READ_DMA_CB_CSR_ERROR_WIDTH 8
#define READ_DMA_CB_CSR_IRQ 1
#define READ_DMA_CB_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define READ_DMA_CB_CSR_MAX_BURST_COUNT 4
#define READ_DMA_CB_CSR_MAX_BYTE 1048576
#define READ_DMA_CB_CSR_MAX_STRIDE 1
#define READ_DMA_CB_CSR_NAME "/dev/read_dma_cb_csr"
#define READ_DMA_CB_CSR_PACKET_ENABLE 0
#define READ_DMA_CB_CSR_PACKET_ENABLE_DERIVED 0
#define READ_DMA_CB_CSR_PREFETCHER_ENABLE 0
#define READ_DMA_CB_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define READ_DMA_CB_CSR_RESPONSE_PORT 2
#define READ_DMA_CB_CSR_SPAN 32
#define READ_DMA_CB_CSR_STRIDE_ENABLE 0
#define READ_DMA_CB_CSR_STRIDE_ENABLE_DERIVED 0
#define READ_DMA_CB_CSR_TRANSFER_TYPE "Full Word Accesses Only"
#define READ_DMA_CB_CSR_TYPE "altera_msgdma"


/*
 * read_dma_cb_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_read_dma_cb_descriptor_slave altera_msgdma
#define READ_DMA_CB_DESCRIPTOR_SLAVE_BASE 0x20000040
#define READ_DMA_CB_DESCRIPTOR_SLAVE_BURST_ENABLE 1
#define READ_DMA_CB_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define READ_DMA_CB_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 512
#define READ_DMA_CB_DESCRIPTOR_SLAVE_DATA_WIDTH 1024
#define READ_DMA_CB_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 16
#define READ_DMA_CB_DESCRIPTOR_SLAVE_DMA_MODE 1
#define READ_DMA_CB_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define READ_DMA_CB_DESCRIPTOR_SLAVE_IRQ -1
#define READ_DMA_CB_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define READ_DMA_CB_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 4
#define READ_DMA_CB_DESCRIPTOR_SLAVE_MAX_BYTE 1048576
#define READ_DMA_CB_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define READ_DMA_CB_DESCRIPTOR_SLAVE_NAME "/dev/read_dma_cb_descriptor_slave"
#define READ_DMA_CB_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define READ_DMA_CB_DESCRIPTOR_SLAVE_SPAN 16
#define READ_DMA_CB_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define READ_DMA_CB_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Full Word Accesses Only"
#define READ_DMA_CB_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * read_dma_cr_csr configuration
 *
 */

#define ALT_MODULE_CLASS_read_dma_cr_csr altera_msgdma
#define READ_DMA_CR_CSR_BASE 0x20000020
#define READ_DMA_CR_CSR_BURST_ENABLE 1
#define READ_DMA_CR_CSR_BURST_WRAPPING_SUPPORT 0
#define READ_DMA_CR_CSR_CHANNEL_ENABLE 0
#define READ_DMA_CR_CSR_CHANNEL_ENABLE_DERIVED 0
#define READ_DMA_CR_CSR_CHANNEL_WIDTH 8
#define READ_DMA_CR_CSR_DATA_FIFO_DEPTH 512
#define READ_DMA_CR_CSR_DATA_WIDTH 1024
#define READ_DMA_CR_CSR_DESCRIPTOR_FIFO_DEPTH 16
#define READ_DMA_CR_CSR_DMA_MODE 1
#define READ_DMA_CR_CSR_ENHANCED_FEATURES 0
#define READ_DMA_CR_CSR_ERROR_ENABLE 0
#define READ_DMA_CR_CSR_ERROR_ENABLE_DERIVED 0
#define READ_DMA_CR_CSR_ERROR_WIDTH 8
#define READ_DMA_CR_CSR_IRQ 2
#define READ_DMA_CR_CSR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define READ_DMA_CR_CSR_MAX_BURST_COUNT 4
#define READ_DMA_CR_CSR_MAX_BYTE 1048576
#define READ_DMA_CR_CSR_MAX_STRIDE 1
#define READ_DMA_CR_CSR_NAME "/dev/read_dma_cr_csr"
#define READ_DMA_CR_CSR_PACKET_ENABLE 0
#define READ_DMA_CR_CSR_PACKET_ENABLE_DERIVED 0
#define READ_DMA_CR_CSR_PREFETCHER_ENABLE 0
#define READ_DMA_CR_CSR_PROGRAMMABLE_BURST_ENABLE 0
#define READ_DMA_CR_CSR_RESPONSE_PORT 2
#define READ_DMA_CR_CSR_SPAN 32
#define READ_DMA_CR_CSR_STRIDE_ENABLE 0
#define READ_DMA_CR_CSR_STRIDE_ENABLE_DERIVED 0
#define READ_DMA_CR_CSR_TRANSFER_TYPE "Full Word Accesses Only"
#define READ_DMA_CR_CSR_TYPE "altera_msgdma"


/*
 * read_dma_cr_descriptor_slave configuration
 *
 */

#define ALT_MODULE_CLASS_read_dma_cr_descriptor_slave altera_msgdma
#define READ_DMA_CR_DESCRIPTOR_SLAVE_BASE 0x20000070
#define READ_DMA_CR_DESCRIPTOR_SLAVE_BURST_ENABLE 1
#define READ_DMA_CR_DESCRIPTOR_SLAVE_BURST_WRAPPING_SUPPORT 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_CHANNEL_ENABLE 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_CHANNEL_ENABLE_DERIVED 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_CHANNEL_WIDTH 8
#define READ_DMA_CR_DESCRIPTOR_SLAVE_DATA_FIFO_DEPTH 512
#define READ_DMA_CR_DESCRIPTOR_SLAVE_DATA_WIDTH 1024
#define READ_DMA_CR_DESCRIPTOR_SLAVE_DESCRIPTOR_FIFO_DEPTH 16
#define READ_DMA_CR_DESCRIPTOR_SLAVE_DMA_MODE 1
#define READ_DMA_CR_DESCRIPTOR_SLAVE_ENHANCED_FEATURES 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_ERROR_ENABLE 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_ERROR_ENABLE_DERIVED 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_ERROR_WIDTH 8
#define READ_DMA_CR_DESCRIPTOR_SLAVE_IRQ -1
#define READ_DMA_CR_DESCRIPTOR_SLAVE_IRQ_INTERRUPT_CONTROLLER_ID -1
#define READ_DMA_CR_DESCRIPTOR_SLAVE_MAX_BURST_COUNT 4
#define READ_DMA_CR_DESCRIPTOR_SLAVE_MAX_BYTE 1048576
#define READ_DMA_CR_DESCRIPTOR_SLAVE_MAX_STRIDE 1
#define READ_DMA_CR_DESCRIPTOR_SLAVE_NAME "/dev/read_dma_cr_descriptor_slave"
#define READ_DMA_CR_DESCRIPTOR_SLAVE_PACKET_ENABLE 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_PACKET_ENABLE_DERIVED 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_PREFETCHER_ENABLE 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_PROGRAMMABLE_BURST_ENABLE 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_RESPONSE_PORT 2
#define READ_DMA_CR_DESCRIPTOR_SLAVE_SPAN 16
#define READ_DMA_CR_DESCRIPTOR_SLAVE_STRIDE_ENABLE 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_STRIDE_ENABLE_DERIVED 0
#define READ_DMA_CR_DESCRIPTOR_SLAVE_TRANSFER_TYPE "Full Word Accesses Only"
#define READ_DMA_CR_DESCRIPTOR_SLAVE_TYPE "altera_msgdma"


/*
 * sram_memory configuration
 *
 */

#define ALT_MODULE_CLASS_sram_memory altera_generic_tristate_controller
#define SRAM_MEMORY_BASE 0x21080000
#define SRAM_MEMORY_IRQ -1
#define SRAM_MEMORY_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SRAM_MEMORY_NAME "/dev/sram_memory"
#define SRAM_MEMORY_SPAN 524288
#define SRAM_MEMORY_SRAM_MEMORY_SIZE 524288
#define SRAM_MEMORY_SRAM_MEMORY_UNITS 1
#define SRAM_MEMORY_SSRAM_DATA_WIDTH 16
#define SRAM_MEMORY_TYPE "altera_generic_tristate_controller"

#endif /* __SYSTEM_H_ */
